### ISSUE TITLE
CORS issue when calling GraphQL endpoint

### ISSUE THREAD

**Issue by alex-r89** [CamiloGarciaLaRotta/watermelon-http-client#154]
Hi there,

Apologies for opening an issue, because I don't think its an issue with the package, but Camilo advised I put this here :)

I am running into a CORS issue when using this Github Action to call my GraphQL backend. I use Express (apollo-server-express) and have set up the action to use an authorization header, much like the mutation example [here](https://github.com/CamiloGarciaLaRotta/watermelon-http-client/blob/main/.github/workflows/graphql_mutation.yml).

I am using JWT to validate the token passed, like so:

```js
// Main.js
import authenticateToken from "../locationHere"

  app.use(authenticateToken, (req, res) => {
    // do things here if authenticateToken doesnt error
  })
```
```js
// Some other file location
const authenticateToken = (req: Request, res: Response, next: any) => {
  // Gather the jwt access token from the request header
  const authHeader = req.headers['authorization']
  const token = authHeader && authHeader.split(' ')[1]
  if (token == null) return res.sendStatus(401) // if there isn't any token
  jwt.verify(token, process.env.TOKEN_SECRET as string, (err: any, user: any) => {
    if (err) return res.sendStatus(403)
    next()
  })
}

```

However, I am getting a CORS error when doing this, I have CORs set up as follows:

```js
  const PROD_LIST = [
    'https://www.mydomain.net',
    'https://mydomain.net',
    'https://hostdomain.com'
  ]

  const corsOptions = {
    origin:
      process.env.NODE_ENV === 'production'
        ? (origin: string, callback: any) => {
            if (PROD_LIST.indexOf(origin) !== -1) {
              callback(null, true)
            } else {
              callback(new Error(`Not allowed by CORS`))
            }
          }
        : 'http://localhost:3000',
    credentials: true
  }
  app.use(cors(corsOptions))
```

I am not too sure how I should go about fixing this? If I work out the origin of the github action, can I just put that into my `PROD_LIST` above and not worry about the auth header? Or should I some how get it working using the authorization header? Or do both auth header and add github action to CORS list some how?

Thanks in advanced for any advice

Just to note, my action is as follows and the request is making it to the server (when I console log out the token):

<details><summary>Github Action</summary>

```js
name: Create New Website Event
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  test:
    name: Create New Event
    runs-on: ubuntu-latest
    steps:
      - name: Create the event
        id: mutation
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          headers: '{"Authorization": "bearer myReallyLongJWTHere" }'
          url: 'https://api.mydomain.net'
          graphql: |
            mutation createEvent($input:CreateEventInput!) {
              createEvent(input:$input) {
                success
                message
              }
            }
          variables: |
            {
              "input": {
                "key":"keyToValidateRequestToResolverIsTrusted"
              }
            }

```
</details>

**Comment by CamiloGarciaLaRotta** [comment]
👋🏽 hey @alex-r89 

>  If I work out the origin of the github action, can I just put that into my PROD_LIST above and not worry about the auth header? Or should I some how get it working using the authorization header? Or do both auth header and add github action to CORS list some how?

JWT and CORS are different concepts 🙂 you need to account for both:
- if your API requires JWT authentication, you must provide it via `"Authorization": "bearer ..."`
- if your API enforces a CORS policy, you must allowlist the origin domain

Now the problem is that I don't know what the origin domain of a GH Action is 😅 you could probably log it in your API server to see if it is always the same. WDYT @titoine54?

**Comment by alex-r89** [comment]
Hey!

Thanks for clarifying. Yeah, I'm not actually using JWT at all in my application, I'm using cookies for auth. The reason I added JWT was simply to use with`watermelon-http-client` as a way to validate the token that comes from the request in the `Authorization` header. 

My concern was "what if anyone just makes this request and calls my mutation - I need to validate that its from my Github action, not just a malicious request". Therefore, I assumed I could validate this request by using the `Authorization` header as in your mutation example. I thought rather than just using a random string, I could use JWT's for this, but maybe this is an over thought?

In regards to the CORS issue - I did log out the request headers and it has no origin header, so I am not too sure what on earth I should do here 😅. The request to my server was as follows: 
```
  headers: {
    connection: 'upgrade',
    host: 'api.mydomain.net',
    'x-forwarded-for': 'IP',
    'x-forwarded-proto': 'https',
    'content-length': '158',
    accept: 'application/json, text/plain, */*',
    'content-type': 'application/x-www-form-urlencoded',
    authorization: 'bearer myReallyLongJWT',
    'user-agent': 'axios/0.19.2'
  },
```

I dont know how I can validate this request, but I think I am confusing how I can validate this request is my github action, and not a random potentially malicious request. My thought is to potentially bypass CORS if an `authorization` header is passed with a token that is correct - but I'm not entire sure if thats correct either!

**Comment by alex-r89** [comment]
Sorry to post again but ive made a bit of progress:

I simply passed an Origin header in my Github Action config, and added this to my CORS allowed list, as follows:

```js
  - name: Create the event
        id: mutation
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          headers: '{"Authorization": "bearer myReallyLongJWTHere", "Origin": "https://github.com" }'
          url: 'https://api.mydomain.net'
          graphql: |
            mutation createEvent($input:CreateEventInput!) {
              createEvent(input:$input) {
                success
                message
              }
            }
          variables: |
            {
              "input": {
                "key":"keyToValidateRequestToResolverIsTrusted"
              }
            }
```

In my apollo-server-express server:
```js

  const PROD_LIST = [
    'https://www.mydomain.net',
    'https://mydomain.net',
    'https://domain.hostdomain.net',
    'https://github.com'
  ]
```
This now works in terms of not getting a CORS error (I am now getting a 500 error). However, now I am concerned - anyone can just make a request to my API if they just put https://github.com as the` Origin` header 😅

**Comment by CamiloGarciaLaRotta** [comment]
>  anyone can just make a request to my API if they just put https://github.com as the Origin header 

hehe yep, this is the reality of any web server: one can ping and make HTTP requests to any public IP. I think as long as you continue relying on an authentication method for your requests you are safe. Up to you if you want to rely on JWT or any other [authentication technique](https://blog.restcase.com/4-most-used-rest-api-authentication-methods/). Just remember to rely on [GH repo secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) to not hardcode your token in the YAML

**Comment by alex-r89** [comment]
Thanks Camilo, I got confused!

I think this makes sense now:

- Include github in my CORS allow list
- pass an Origin header in my yml file
- pass an authentication header with a JWT
- validate this JWT on my backend for this particular resolver

Thanks very much for helping with this question!
