### ISSUE TITLE
Update to Node.js 16

### ISSUE THREAD

**Issue by rvanderlinden** [CamiloGarciaLaRotta/watermelon-http-client#246]
Hi! 👋🏽

**Is your feature request related to a problem? Please describe.**
We are receiving deprecation warnings for this action because Node.js 12 actions are deprecated. If the deadline is not postponed, this action may stop working in Summer 2023. I have outlined the deprecation warning below.

`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: CamiloGarciaLaRotta/watermelon-http-client@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

**Describe the solution you'd like**
Please update this action to use Node.js 16 so we can keep using it in the future.

Thanks 😄 !
Roland

**Comment by CamiloGarciaLaRotta** [comment]
Hey @rvanderlinden!

I'm currently on a trip AFK, but happy to do so once I come back online.

Feel free to put up a PR too, we can get it merged ASAP

**Comment by CamiloGarciaLaRotta** [comment]
ahhh turns out we had already bumped it! we just hadn't released a new version. Let me make sure we are all up to date and release a new tag

https://github.com/CamiloGarciaLaRotta/watermelon-http-client/pull/233

**Comment by rvanderlinden** [comment]
@CamiloGarciaLaRotta This issue is now resolved, thank you! :)
