### ISSUE TITLE
Update the set-output command

### ISSUE THREAD

**Issue by rvanderlinden** [CamiloGarciaLaRotta/watermelon-http-client#247]
Hi! 👋🏽

**Is your feature request related to a problem? Please describe.**
We are receiving deprecation warnings for this action because the `set-output` command is deprecated and will be disabled in the near future. If the deadline is not postponed, this functionality and the action itself may stop working on 31st May 2023. I have outlined the deprecation warning below.

`Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Describe the solution you'd like**
Please update this action to use environment files instead of `set-outpout` as outlined in this [guide](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

Thanks 😄 !
Roland

**Comment by CamiloGarciaLaRotta** [comment]
the docs say [we should update](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows) `@github/core` to at least 1.10.0 🤔 that seems to [already be the case](https://github.com/CamiloGarciaLaRotta/watermelon-http-client/blob/main/package.json#L28). @rvanderlinden mind pointing me to where you see that we are still using the old `set-output`?

**Comment by rvanderlinden** [comment]
In case it matters, this is our usecase for posting a message to Slack:

```
    - name: Slack test message
      id: slackrequest
      uses: CamiloGarciaLaRotta/watermelon-http-client@v1.6
      with:
        url: 'https://slack.com/api/chat.postMessage'
        method: post
        headers: '{
          "Authorization": "Bearer ${{ secrets.SLACK_BOT_TOKEN }}", 
          "Content-Type": "application/json" 
        }'
        data: '{ 
          "channel": "<redacted slack channel id>", 
          "username": "${{ github.workflow }}",
          "icon_url": "<redacted icon url>",
          "text": "Test message to slack."
        }'
```

**Comment by CamiloGarciaLaRotta** [comment]
Happy to 🍐with you or review any PR that you soon for this issue 🙃

In the meantime I'll try to reproduce on a dummy repo

**Comment by CamiloGarciaLaRotta** [comment]
🙇🏽‍♂️ @rvanderlinden mind testing your repo's workflow with the latest version:  [v1.7](https://github.com/CamiloGarciaLaRotta/watermelon-http-client/releases/tag/v1.7)

```yaml
steps:
    - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.7
```

**Comment by rvanderlinden** [comment]
@CamiloGarciaLaRotta That was harder than expected, good find! 

I have tested `@v1.7` and the warnings no longer appear. Looks like this issue is resolved, thank you! :) 

It looks like `@v1` still has the warnings. I assume this either requires a manual delivery-step from you or perhaps it's a caching issue that will resolve in due time?

**Comment by CamiloGarciaLaRotta** [comment]
🙃 most likely caching, because v1 should already take the latest 1.* Release

**Comment by rvanderlinden** [comment]
Thanks again!

**Comment by rvanderlinden** [comment]
Hi @CamiloGarciaLaRotta! To get back to my question regarding the `@v1` not behaving similarly to `@v1.7`: I just found out that the actual `v1` tag has to refer to the latest release commit in order for version overriding to work. So right now, I think the `@v1` does actually use the older `v1.4` tag (see screenshot) and not the `v1.7` tag, which we both presumed would happen automatically. I will be referencing `v1.7` from here on out, perhaps this is something you could update or outline in the readme :)

<img width="450" alt="image" src="https://github.com/CamiloGarciaLaRotta/watermelon-http-client/assets/29040965/9b5dc37e-37d7-4672-9557-6610202e7983">

See also this thread: https://github.com/orgs/community/discussions/48058#discussioncomment-5055159.
